//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.MBRDCMDMI_ProyectoIPS.MBRDCMDMI
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "MBRDCMDMI_DSLPracticaMDDIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"MBRDCMDMI_ProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID MBRDCMDMIDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MBRDCMDMICommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID MBRDCMDMIExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MBRDCMDMICommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewMBRDCMDMIExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(MBRDCMDMICommandSetId), 0x0001);
	
		// Package identifier
		public const string MBRDCMDMIPackageId = "7a02d929-fdb9-43c6-a963-58daf1971f30";
		
		// Editor factory identifier
		public const string MBRDCMDMIEditorFactoryId = "3bf5f4be-ebdb-4a75-b685-c3723eed8fc7";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string MBRDCMDMIModelExplorerToolWindowId = "429f8d45-caef-468c-8efe-2c25b26cef26";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.MBRDCMDMI_ProyectoIPS.MBRDCMDMI
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string MBRDCMDMICommandSetId = "926ea2c0-3855-4c3d-8401-585e79bc14e7";
	}
}